freshpaint-io/freshpaint-gtm-template

template.tpl

Provide Freshpaint-GTM-template support for Google Ads.
Supports all fields the Native-GTM Google ads type supports.
Tested E2E with Google Ads (Freshpaint account), observed conversion value posted.

FP-1041 Add Google Ads support

---

template.tpl

* Fix param name casing on googleAdsEventName
* Ensure all ga4-specific param names have ga4 prefix

FP-1064 Rename params to avoid name collisions

---

template.tpl

both top-level and subparam names share the template-wide namespace
this change ensures that all destination-specific names have a destination-specific name prefix

FP-1064 fix subparam naming for template namespace

---

template.tpl

* Destination names now match Freshpaint destination names (since that's what they send to)
* Bing and Twitter param names changed to align with source native-GTM bing tag type, simplifying migration script
* Bing pageViewSPA event action removed, as it's not currently supported by Freshpaint destination (migration script logs an error if any tags with these are present)

Fp 1064 fix bing names, remove unsupported bing pageViewSpa, rename destinations to match Freshpaint

---

template.tpl

GTM GA4 (both native and Freshpaint versions) supports optional user props
When these are specified, this call is currently being used:
`
identify("", props, options);
`
* This causes a previously set $user_id to get clobbered with the new value "".
The corrected syntax is below, which preserves any previously-set identity:
`identify(props);`;
* The options arg is removed, since it seems to have no effect when used with identify and the single props arg.

FP-1127 fix GTM GA4 identify to not clobber userid

---

template.tpl

* theTradeDesk type added
* template UI
* js handler (track)
* fixed pre-existing issue with parsing a PARAM_TABLE (was not working for twitter ads, now fixed)
* fixed pre-existing facebook issue where the default standard event, pageview, was not selected properly
* fixed pre-existing facebook issue where SubmitApplication was missing from standard eventnames list
* fixed pre-existing identify issue where userid not prompted for
* changed commonEventName prop display name to 'Freshpaint Event", to differentiate it for theTradeDesk where the ttd-specific event name is optional, and often omitted
* refactored to use data.gtmOnSuccess() and gtmOnFailure() consistently, with a log message preceding every gtmOnFailure() 
* Used a local site with GTM tag installed for fptest GTM container
* …

FP-1279 Add theTradeDesk type, fix identify, fix fb default standardEvent

---

template.tpl

This adds a stackadapt event type to our GTM template
Resulted in the following event in snowflake:
```
{
"event": "stack adapt test",
"properties": {
"$browser": "Chrome",
"$browser_version": 114,
"$current_url": "https://gtm-msr.appspot.com/render2?id=GTM-WP69WFQ5",
"$device_id": "189d58cd85637-0f406e788faea1-26031d51-100200-189d58cd8576e",
"$device_type": "Desktop",
"$eventDefProps": {},
"$event_name": "stack adapt test",
"$gtm": true,
"$host": "gtm-msr.appspot.com",
"$initial_referrer": "https://gtm-msr.appspot.com/render?id=GTM-WP69WFQ5",
"$initial_referring_domain": "gtm-msr.appspot.com",
"$insert_id": "qmvle3b2j486ffwu",
"$ip": "66.102.8.131",
"$lib_version": "1.3.0",
"$options": {
"integrations": {
"All": false,
"StackAdapt": true
}
},
"$os": "Windows",
"$pathname": "/render2", …
```

FP-1289 gtm template for stackadapt

---

template.tpl

Making underlying `dest_config_names` a first-class-citizen prop for the two that currently need & implement it in the destination: Facebook, theTradeDesk
* Adhoc on fptest
* Verified `dest_config_names` in payload, when form field populated, for Facebook
* Verified `dest_config_names` in payload, when form field populated, for theTradeDesk
Example for Facebook:

FP-1279 add Freshpaint Config Names field for Facebook, theTradeDesk

---

template.tpl

* Template originally written to support both tracker_id and upixel_id
* In our current scope and pilot, we plan to support only tracker_id, therefore removing upixel_id as a selectable option for now

FP-1306 disable theTradeDesk upixel_id option

---

template.tpl

* Adding support for addEventProperties to the Freshpaint GTM Template - this is required to support GA4 "Shared Event Properties"
* Resequenced the type list to have most popular destinations first
* Tested locally with required perfalytics-js change from https://github.com/freshpaint-io/perfalytics-js/pull/162, observed shared props coming thru on new events

FP-1414 Add support for addEventProperties

---

template.tpl

* Purpose described in linked linear ticket below
* Changed display name to indicate deprecation

FP-1752 Deprecate init

---

template.tpl

* Adds Google Ads call conversions template
* Tested with fptest gtm container, and associated local test site, along with a current gclid fetched from snowflake for freshpaint google ads acct, observed the original 312-555-1212 nbr got changed in both displayed text and linked text

FP-1841 Add Google Ads call conversions template

---

template.tpl

With the changes to freshpaint-gtm.js (a prereq before this is deployed), an envID no longer needs to be passed with every operation (track, identify, addEventProperties).
The deprecated 'init' tag subtype is the only action which requires and does anything with a stored envID parameter.
This greatly simplifies most GTM configurations - those not loading the Freshpaint snippet from a GTM Custom HTML tag don't require an environment ID anywhere in the GTM container.
Another change: Freshpaint debug is no longer set by the Freshpaint GTM template (resulting in fewer console messages, unless the user explicitly sets debug true from the console)
See [FP-1946](https://linear.app/freshpaint/issue/FP-1946/gtm-proxy-script-fixes-for-config-clobbering-preventing-multi-env) for additional …

FP-1946 Remove need for envID for all but init

---

template.tpl

I originally copied the column names from the twitter param_table, but apparently they have to match the native floodlight tag column names for the migration script to work.

[FP-2094] Change floodlight param table column names

---

template.tpl

Multi-config for Facebook cAPI, using the generalized multi-config approach.
This gives more context on the gtm template versions we'll need to release: https://www.notion.so/freshpaintio/RFC-Multi-config-migration-approach-from-workarounds-to-generalized-solution-cd892bbcee1d499893103908f0f40219?pvs=4#3acbe68c68b04f0d9294251c4032b370
* If only the old commonDestConfigNames param is present, it is still used to populate the dest_config_names prop

CA-11 Add updated multi-config support for Facebook cAPI

---

template.tpl

Fixes a regression from #35 where the Floodlight enhanced conversions field group showed up regardless of selected tag type. This group should only be displayed for Floodlight
Before:
After:
Still works with floodlight

Bug: Only show enhanced conversion group for floodlight

---

template.tpl

* https://linear.app/freshpaint/issue/CA-40/gtm-template-updated-for-multi-config-for-ga4-proxy-google-ads
* [RFC: Multi-config migration approach from workarounds to generalized solution](https://www.notion.so/freshpaintio/RFC-Multi-config-migration-approach-from-workarounds-to-generalized-solution-cd892bbcee1d499893103908f0f40219#c815385661854cbdbdc3dfc5a7deebe8)
* Removed 'init-OBSOLETE' tag from subtype dropdown
* Retested on fptest-buc+test - an existing 'init' tags continue to be a nop (no error) 
* Tested all permutations (no override, single override, multi-override) for the affected destination types, on GTM container fptest-buc+test

CA-40 Add GA4-proxy, Google Ads, theTradeDesk generalized multi-config support

---

template.tpl

track and identify now support specifying opt-in or opt-out destination types / instances

CA-38 Add integrations obj capability to track, identify

---

template.tpl

Reduce GTM template load times from ~50-60s to ~20s and resolve error with GTM migration template upgrade
Tested with GTM container `fp-buc-copy` on static site
- Successfully ran migration using local `template.tpl` file
- Verified events successfully ingested for each destination with Live View
- Verified `identify` events present in Live View on tag trigger
- Verified `track` events present in Live View on tag trigger
- Verified `addEventProperties` in Live View augments events with properties specified in tag

CA-69 Fix GTM template load times

---

template.tpl

From discussion with @bucrogers yesterday, we discovered that even though there is a custom params table in the bing ads tag in the freshpaint template, we don't use it for anything. Given there is no current use case for supporting this custom table and to avoid future confusion, we're opting to remove it until it becomes necessary.

CA-95: remove unused bing custom params table

---

template.tpl

Primarily adds a template subtype for TikTok Ads.
* track now includes TikTok ads as a select option
* identify narrowed down to only those dests supporting identify
testenv: fptest-buc+test

CA-312 Add TikTok Ads

---

template.tpl

Testing:
* Validated that a GTM tag can be configured for CM360 and sends to Freshpaint
* Validated that a tag with a specific instance ID configured sends only to that instance
* Validated that a generic track tag with CM360 in the opt-in list sends to CM360
* Validated that custom properties correctly forward with events

Add support for Google CM360 tags

---

template.tpl

Primary change: Remove theTradeDesk extraneous props
Primarily retesting of TTD to ensure no regression, json parsing works for 2 json props
* ttd-value-items comes through, but  ttd-optional-props never does

FP-2484 Remove theTradeDesk obsolete props, clarify CM360 help text

---

README.md
template.tpl

see linear tix for scope
* Did both pinterest and reddit in one PR to quicken the gallery update cycle
* Tested on gtm container: fp-test-buc+test

FP-2685 FP-2687 Add Reddit Ads, Pinterest Ads

---

template.tpl

I was able to test this by importing the template file into GTM and verified that the options argument is now passed to identify correctly

FP-3045: Fix identify. Options must always be passed third.

---

template.tpl

This PR adds multi-config support for Pinterest Ads.
~~**NOTE**: I've never worked with GTM templates before and am basically cargo-culting from existing examples where we've added multi-config support to other destinations. Never even cloned this repository before, so please carefully scrutinize with skepticism.~~
I've synced with @bucrogers who guided me through how to verify the changes I've made to the template. I can attest that GTM tags targeting the the Pinterest Ads destination definitely work as expected re: multi-config support.
See also: https://freshpaint-io.slack.com/archives/C08BREKLLNA/p1741625101585299

Add multi-config support for Pinterest Ads TAN-152

---

metadata.yaml

This PR releases the recent update to our GTM template that adds support for Pinterest Ads multi-config.

Release Pinterest Ads multi-config support TAN-152

---

metadata.yaml

This PR corrects the git commit SHA we use to reference the right version of the codebase for releasing GTM to the GTM gallery.

Use most recent MERGE commit SHA1 TAN-152

---

template.tpl

This PR converts all impact.com fields we can clearly identify as containing numeric data to numbers in the GTM script.
Tested this against a test container.

Convert impact.com numeric fields to numbers TAN-173

---

template.tpl

https://linear.app/freshpaint/issue/TAN-262/add-support-for-the-numeric-value-field-for-ttd-warby-parker
Previous PR:
https://github.com/freshpaint-io/freshpaint-gtm-template/commit/4ee887f3d5ce66b9dedef15b15d87cd5c5c96ffa
Just added value and currency back in.

Adds back ttd value and currency

---

template.tpl

To allow for these text1-text10 options to come up for impact's conversion tracker event dropdown.

Adds text1-10 for impact gtm migration

---

template.tpl

See ticket for container export.
Tested with impacted customer. 'Standard' counting is a safe default for customers migrated before other counting methods were supported.

Default to standard counting method for CM360 floodlight counter if not specified

---

template.tpl

Tested with published GTM container.
order_id now has default behavior and is not required to be provided by the user.

Don't require order_id for MNTN

---

template.tpl

Two primary changes:
1. GA4-proxy now supports an optional Event Properties Variable. This allows usage of the Google Tag Shared Event Properties Variable on FP GA4 event tags. Before, the GTM Migration would propagate all props from the Google Tag Shared Event Properties Variable to each FP GA4 event tag referencing it,  resulting in duplicated data in GTM and making the migration harder to review / validate.
2. LinkedIn Ads Conversion API now supports free form properties entry. Since the LinkedIn Ads cAPI now supports various properties like email, unlike the LinkedIn Ads destination, these need to be supported via GTM.
* Moved LinkedIn Ads to the bottom of the UI-picker lists for subtype and track opt-in. 
* In each case, verified proper events sent to Live View

IND-1524 add ga4 shared ev prop, LinkedIn cAPI props

---

src/generatedParameters.json
src/parameters/integrations/linkedinCAPI.ts
src/web.js
template.tpl

We're supporting Multiconfig for LinkedIn CAPI. This allows the user to specify instance names. 
Tagging @tiffanyhan just because this is my first time contributing since the repo restructure and I want to make sure I didn't miss anything! 
- instance ID on integrations object when provided
- integrations object left generic when instance ID not provided

LinkedIn CAPI instance id support

---

src/generatedParameters.json
src/parameters/integration.ts
src/parameters/integrations/siriusxm.ts
src/web.js
template.tpl

Adds in GTM tag for SiriusXM. Supports multi-config with an option to specify AppName to only send events to a particular instance.
example generic event (confirmed this showed up in all siriusxm instances)
example of app name specific event (confirmed this did not show up in other instances)
this requires a property of `$siriusxm_aid` to be in the property fields of the given tag in GTM. it is also expected of the generic freshpaint js code (e.g., send `$siriusxm_aid`  in the body of custom event). i'm not sure if that's actually the behavior we want for customers.
**update:** i think this is fine as is. the event processing code should pull from impression event, i just don't have testing data for that yet.

SiriusXM GTM
